---
##########################
# docker registries

docker_registry: index.docker.io
docker_registry_ansible: quay.io
docker_registry_service: index.docker.io

##########################
# versions

manager_version: 7.0.4


##########################
# ara

ara_enable: true
ara_server_host: "{{ hostvars[inventory_hostname]['ansible_' + internal_interface]['ipv4']['address'] }}"

##########################
# netbox

netbox_enable: true
netbox_api_url: "http://{{ hostvars[inventory_hostname]['ansible_' + internal_interface]['ipv4']['address'] }}:8121"

##########################
# celery

celery_enable: true
flower_host: "{{ hostvars[inventory_hostname]['ansible_' + internal_interface]['ipv4']['address'] }}"
osism_api_host: "{{ hostvars[inventory_hostname]['ansible_' + internal_interface]['ipv4']['address'] }}"

##########################
# configuration

configuration_directory: /opt/configuration
configuration_git_private_key_file: ~/.ssh/id_rsa.configuration
configuration_type: git

configuration_git_host: github.com
configuration_git_port: 22
# yamllint disable rule:line-length
configuration_git_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCb2O0Hflexf3B55j81SPde8OCkEOs3y49+NdSXBRcpI4m8n4nvqwwK4M/hKJv3bYFHazgW/NuYjp5lrdA68AecVBJBb2l3Tp0dFsc7f4uMMWTJrzssIAnA6tOOgj+t7KRTmmo9j8BuDeY701PIyM2UZe/XOLLIqn+SSxx8PXCm+X2VJimy3up734HexvR6lTfMCMrWIaKLFSKA2a9+lBVDCsDoWznkALrKaY4us89BQHr5AbmFeXfUEJl/wPRFsBiHAZGVYnawyvF3RZt1NnYBhroonm1N1xjmrYoiQ+pctvo3mLFZ+9E7IuuvT01WH3M0EKV5glDmVGgZ84nK7d0RsonUHhXlT/yFJ72g+hEVoMqszNjpyo4BbpHvwNwmoTPlXF3v+fRPVjge8FU1SjHqCiX7wOJrxZOEHtLGX7Sjc6wZTwtgu6H5TxpYJcLYNK4O7ZQM9peqPud4k61fDIs0WyxQt2uW/P2IMIGHLdi/oncSZl79D9fggFjrBLCnrIhgyvfdAVnTyw5VnhUzKqxCQIjTl4GkVFGUxOFKP484AAovARKehdyRtMzo8ae8onBAu5JYI95hmb8EonqTav5S7kAEN1ArogrGHqGCEXcEYLb47HZcPexxx1Opaqu/rxPqXxyhs9Rjl5mZ1Q8wxmzHM8HJK+kLKMYl4l0w1QUtBQ==
# yamllint enable rule:line-length
configuration_git_protocol: ssh
configuration_git_repository: jpvargasit911/it911cloud
configuration_git_username: jpvargasit911
configuration_git_version: main
