---
##########################
# docker registries

docker_registry: index.docker.io
docker_registry_ansible: quay.io
docker_registry_service: index.docker.io

##########################
# versions

manager_version: 7.0.4


##########################
# ara

ara_enable: true
ara_server_host: "{{ hostvars[inventory_hostname]['ansible_' + internal_interface]['ipv4']['address'] }}"

##########################
# netbox

netbox_enable: true
netbox_api_url: "http://{{ hostvars[inventory_hostname]['ansible_' + internal_interface]['ipv4']['address'] }}:8121"

##########################
# celery

celery_enable: true
flower_host: "{{ hostvars[inventory_hostname]['ansible_' + internal_interface]['ipv4']['address'] }}"
osism_api_host: "{{ hostvars[inventory_hostname]['ansible_' + internal_interface]['ipv4']['address'] }}"

##########################
# configuration

configuration_directory: /opt/configuration
configuration_git_private_key_file: ~/.ssh/id_rsa.configuration
configuration_type: git

configuration_git_host: github.com
configuration_git_port: 22
# yamllint disable rule:line-length
configuration_git_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCxrt5A+HFp+YwxG2dO+WZlWSD8v5CvRFbFMTmbVk3zIXaAQJayDY0vw7KaNi8xvt2lxnGe3etBuP6yPnyL6PFSTvE4YL2dGmJIUW6iYuV5Nu0fOPmQZPRMcd+v2NpDd082JHjb7IF5DPm0CwE97H8Fr6w+rWEVs22CECFIC2Lv4xh9ogagAAFRnTgyLYhzGn/pmRSaiuSeBmOPCMBQviEwHWXjNdrbYftVs70Yh/WWaa8k06QzYh3IBIZ68dnuhtygyZmEkiAMyQWxpCsZK0wQaZpr76wfcK4JgjxybeRHZDdRNO09b/gZlkqby1C2I80wcpUVn+4wyTx/NuaMyRT7vwRY+Uq8zObsDPOgUecsfTqDxlnMjhhAFmY3i0YVOH0wnew7T079W/yhxiRzifG2S8/WLSFHqq9jxj258p+nMGTyDqcWQOXWsqj82kWI2kUrTs5YkEwaWFUBstAh1bTEQFGvBG3ga672ZhbrrbtW28Xe4oz6G4TR6F9YgJG4mS0+sUcq+gJjNMkpzi5YeqA2ZpOpMrNNNYL9OiRfbSEXlsX1Sn80Sgj4IPAJTCrptIRqQxsXknrxC1JnRgVrN6d3596i77wmHzIrPdUPOxagbj75AVSlUbdyJ1weS/M/7Bwy1ovrR3j4Enoir4mKRpMICQt4bToOclKly2zGIaYuBQ==
# yamllint enable rule:line-length
configuration_git_protocol: ssh
configuration_git_repository: jpvargasit911/it911cloud
configuration_git_username: jpvargasit911
configuration_git_version: main
