---
##########################
# docker registries

docker_registry: index.docker.io
docker_registry_ansible: quay.io
docker_registry_service: index.docker.io

##########################
# versions

manager_version: latest

ceph_version: quincy
openstack_version: 2023.2

##########################
# ara

ara_enable: true
ara_server_host: "{{ hostvars[inventory_hostname]['ansible_' + internal_interface]['ipv4']['address'] }}"

##########################
# netbox

netbox_enable: true
netbox_api_url: "http://{{ hostvars[inventory_hostname]['ansible_' + internal_interface]['ipv4']['address'] }}:8121"

##########################
# celery

celery_enable: true
flower_host: "{{ hostvars[inventory_hostname]['ansible_' + internal_interface]['ipv4']['address'] }}"
osism_api_host: "{{ hostvars[inventory_hostname]['ansible_' + internal_interface]['ipv4']['address'] }}"

##########################
# configuration

configuration_directory: /opt/configuration
configuration_git_private_key_file: ~/.ssh/id_rsa.configuration
configuration_type: git

configuration_git_host: github.com
configuration_git_port: 22
# yamllint disable rule:line-length
configuration_git_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDaUGLbR2knEMNAFET+65kRL2quY6QAaa1KbBJQu7oWo2Wd7Ne04E4THMBxInpPiS/37gfAenrW+2nMJJBNws/uj6/cWV+QZecUkvUfILn0R3qFEFJsAJ6oc9dgYRk05aI0C3JKUJaUBq+1ZBSFg1TsnVuLypC4GcsmAwYA2Uj4+9/b25OfCsMqgeiTsdg/bejedWMgObSBr3bjoTFNGE5oQof0EtriwbsacaP/ZzDs3qV/as8xjZnlXR3xqkpWvL69ozINpoBNHr3RoaPZJixNJo5NbruyuatVyza6Y15W3pl0D20ueJR2bcPdOh0GPs0QRVLE80851C6mcYmO2frTjpmYurBSPXI3xCQmBqwKmLzkfSL33e1c60kmh5CN+egMW89I/uh54fkFs+hJ+Z9F/w8BqK0VPwKQo2eEMjw7LNHbGVyC0sj6EtA1x36mjhR1laPe7fbVn2GaG7acju0zNG9UzMjfp/nR8hxFxr7IbOdLdPufo1IRVk8w6RIFOwILFPIm9bjN4NoHPncUS8q80FIyWclkSMulsXQez9G/QBHqQiSK72AXPDQwUD106KPw11DNnIlayV2z1yoTmE9sE7w/UPydZ0fNmSoojASBvBHJjf3Y+k2QcmjwzmQ7b4SpeIKt3dOpwW6H+gksUzq+q2inANLIhwNkl0E8cxMJiw==
# yamllint enable rule:line-length
configuration_git_protocol: ssh
configuration_git_repository: jpvargasit911/it911cloud
configuration_git_username: jpvargasit911
configuration_git_version: main
