---
##########################
# docker

docker_version: '5:24.0.9'
docker_user: "{{ operator_user }}"

##########################
# operator

operator_user: dragon

# yamllint disable rule:line-length
operator_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDREIZU6MDKarGo5NbVQddwOlKYhWSZTVi8QVAtxYW6otsbVRTiH00PeV8XJJiQqiMYj5k9Q15aDJwP0r/f117zgX7VsM7tSRO4bGNtznxCoE3ioYyFF4oGb3AEfjHoc3CXNQ9ZBZLNryATgFTX4eeEaVqJYsIta3uDs16iffc/ElnKjIYi/kWd/uSUdGBkEaRtAVq8tMqGB/qC6lEbWjDoM9Laxf26tThLTmAQs1AbYwbFv6yCE8VjW1ys/r8cO90ipHScflSZGtNdelOsMjF+pJinbzzroB9bREBwXaFxR5aGYVa0/VnphVX1uBrOkrnfVzVM+PZq4lF+Dw3XuDXkuVxw23o4bTJMUncj4GLlQo4Y+2HvUGZBFKk6uFDBEDBy0l1PyW4TTn9UY3b00UCQuxxgseNBUGHShTW651M7hHkLvd3lvqgX2jf7K/u3eNeJ1+EUwSUN31CGmchKiBBZ4TpPLr4CGbv8aBzqkvHZ+GngEUeqYxrDvBFi5tbwZjYiDo3nr7hOiaolFbTn/otOz/0I9RSnIyiXrjt928Ij6U2ReHyegMsxizyiqfQ5HL386cGo7HsFuwASXw1Ee7NpUjQDykOLi23ROIG52ONdn8bKqKjSkWKM6YdsgyC00z8/kAFZYK9ITpJlX+60IebzkuRXjSEFes5S2JAqBM2gxQ==
# yamllint enable rule:line-length

operator_authorized_keys:
  - "{{ operator_public_key }}"

##########################
# resolvconf

# NOTE: As it is not trivial to comfortably query several entries for a parameter
#       with Cookiecutter, only one DNS server is added here. At least one additional
#       DNS server should be added.
# DOCS: https://osism.tech/docs/guides/configuration-guide/commons/resolvconf
resolvconf_nameserver:
  - 10.40.5.249
resolvconf_search: osism.maas

##########################
# hosts

hosts_additional_entries:
  api-int.osism.maas: 10.40.6.251
  api.osism.maas: 10.40.6.250

##########################
# chrony

# NOTE: As it is not trivial to comfortably query several entries for a parameter
#       with Cookiecutter, only one NTP server is added here. At least one additional
#       NTP server should be added.
# DOCS: https://osism.tech/docs/guides/configuration-guide/services/chrony
chrony_servers:
  - de.pool.ntp.org

##########################
# ceph

ceph_cluster_fsid: 0f162f8c-4bfa-45f8-9b59-4314f379e1a2
