---
##########################
# docker

docker_version: '5:26.1.4'
docker_user: "{{ operator_user }}"

##########################
# operator

operator_user: dragon

# yamllint disable rule:line-length
operator_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC/DLpFwjys08pL1NjZPwBhi+sLYr7ciAlMfV8omuwGPiK1JfijWut0TEJOluPKKP9+25AEnNCoULwJGUU5Znfg+WbdYgmI1XYDH0eyG0raXFqbgGQV+sME//U4qRSNFubFZmgpeNoay/JzSOmAQIAAH6xdtDe3P6ribeNE3sKDKcGX9DAQ1JLpDKEvFrARjGWKwTHo/MoYQ+ELQzSfzThOMMVKn8EmCRhlDbVESSGIJHGSN5qpVXUTlMft7DNbFA1Ms5CmEKNIXbIgDa/MAevPayFePqRF/Yz4bLuyQ5WKi0LR2eSqbtkrIkhQ19mCxeaWwL7W92kFFzSvtyPM5r7IH4YPvnYQ7JVr1edV5kybRrIr+gJsTB8JiC3KWYp8ztJr4ywms97dOSRZ2n+im5Z17zwSDWiGVFuGCnRrwMd0k1CxAzFvnH2TXn5SLHTaJ3lQRBROY7VIqTKek6bSYIZ2Q2Rw4G4zcXX71k77uC/BF1GVUkMLi44s6QOEHtRKqwFG4ktdxD5z7QI8ikw5YT/8cWfIW9q+0Mo23ZHmyl7iuRzDFuM5bXJBc+UEXwMbolENBZS6Mhi7qbNCwmqUPKgF89MLtWEAzg9+H1nk1Dpcy2S9IimMr1u5Md5uj+qfZEC5Im0Mlt612knFuXr6qxmYwiWESkQL7P/tnakJ78fScw==
# yamllint enable rule:line-length

operator_authorized_keys:
  - "{{ operator_public_key }}"

##########################
# resolvconf

# NOTE: As it is not trivial to comfortably query several entries for a parameter
#       with Cookiecutter, only one DNS server is added here. At least one additional
#       DNS server should be added.
# DOCS: https://osism.tech/docs/guides/configuration-guide/commons/resolvconf
resolvconf_nameserver:
  - 10.40.5.249
  - 8.8.8.8
resolvconf_search: maas

##########################
# hosts

hosts_additional_entries:
  api-int.maas: 10.40.5.1
  api.maas: 10.40.5.1

##########################
# chrony

# NOTE: As it is not trivial to comfortably query several entries for a parameter
#       with Cookiecutter, only one NTP server is added here. At least one additional
#       NTP server should be added.
# DOCS: https://osism.tech/docs/guides/configuration-guide/services/chrony
chrony_servers:
  - de.pool.ntp.org

##########################
# ceph

ceph_cluster_fsid: 3dffe182-1816-4d27-803b-ae784c9278a6
