---
##########################
# generic

fsid: 0f162f8c-4bfa-45f8-9b59-4314f379e1a2

##########################
# network

public_network: 10.40.6.0/24
cluster_network: 10.40.6.0/24

##########################
# custom

ceph_conf_overrides:
  global:
    auth allow insecure global id reclaim: false
    osd pool default size: 3
  mon:
    mon allow pool delete: true
  "client.rgw.{{ hostvars[inventory_hostname]['ansible_hostname'] }}.rgw0":
    "rgw content length compat": "true"
    "rgw enable apis": "swift, s3, admin"
    "rgw keystone accepted admin roles": "admin"
    "rgw keystone accepted roles": "member, admin"
    "rgw keystone admin domain": "default"
    "rgw keystone admin password": "{{ ceph_rgw_keystone_password }}"
    "rgw keystone admin project": "service"
    "rgw keystone admin tenant": "service"
    "rgw keystone admin user": "ceph_rgw"
    "rgw keystone api version": "3"
    "rgw keystone implicit tenants": "true"
    "rgw keystone url": "http://api-int.osism.maas:5000"
    "rgw keystone verify ssl": "false"
    "rgw s3 auth use keystone": "true"
    "rgw swift account in url": "true"
    "rgw swift versioning enabled": "true"
    "rgw verify ssl": "false"
