---
##########################################################
# images

docker_registry: quay.io

##########################################################
# loadbalancer

kolla_internal_fqdn: api-int.maas
kolla_external_fqdn: api.maas

kolla_internal_vip_address: 10.40.5.1

# kolla_enable_tls_internal: "yes"
# kolla_enable_tls_external: "yes"

# kolla_copy_ca_into_containers: "yes"

##########################################################
# openstack

# disable services
enable_heat: "no"

# generic
openstack_service_workers: 5

# elasticsearch
opensearch_heap_size: "4g"

# neutron
neutron_plugin_agent: "ovn"
neutron_ovn_availability_zones: [nova]
neutron_dns_domain: maas.

# octavia
octavia_network_type: tenant

# designate
designate_ns_record: openstack.maas

##########################################################
# ceph rgw integration

enable_ceph_rgw: true
enable_ceph_rgw_keystone: true

ceph_rgw_swift_compatibility: false
ceph_rgw_swift_account_in_url: true

##########################################################
# external ceph

cinder_backend_ceph: "yes"
glance_backend_ceph: "yes"
gnocchi_backend_storage: "ceph"
nova_backend_ceph: "yes"

ceph_gnocchi_pool_name: "metrics"
cinder_backup_driver: "ceph"
glance_backend_file: "no"

ceph_nova_user: nova

# NOTE: public_network from environments/ceph/configuration.yml
ceph_public_network: 10.40.6.0/24

#########################################################
# other
